[package]
name = "oui_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
scraper = "0.19.0"
csv = "1.3.0"
tokio = { version = "1", features = ["full"] }